$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: sweep_registered_component
display_name: image component training
description: registered component for training image models

component: azureml:/subscriptions/381b38e9-9840-4719-a5a0-61d9585e1e91/resourceGroups/automlimage_eastus2_rg/providers/Microsoft.MachineLearningServices/workspaces/risha-ws-eastus2/components/train_object_detection_model/

inputs: 
  training_data:
    type: mltable
  validation_data:
    type: mltable
  model_name:
    description: Model name
    type: string
    default: yolov5
    enum: ['yolov5', 'fasterrcnn_resnet18_fpn', 'fasterrcnn_resnet34_fpn', 'fasterrcnn_resnet50_fpn', 'fasterrcnn_resnet101_fpn', 'fasterrcnn_resnet152_fpn', 'retinanet_resnet50_fpn']
  learning_rate:
    description: Initial learning rate
    type: number
    optional: true
    min: 0
    max: 1
  number_of_epochs:
    description: Number of training epochs
    type: integer
    optional: true
    min: 1
  optimizer:
    description: Type of optimizer
    type: string
    default: sgd
    enum: ['sgd', 'adam', 'adamw']

outputs:
  model:
    type: mlflow_model
