$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_model
display_name: train_model
version: 1

component: azureml://registries/azureml-staging/components/train_object_detection_model/versions/0.0.1-prelease

inputs: 
  training_data:
    type: mltable
  validation_data:
    type: mltable


outputs:
  model_output:
    type: mlflow_model
  test_data:
    type: uri_folder
