$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: image-setting-translation
description: Translates image settings into sweep job object using a built-in component.

compute: azureml:gpu-cluster-nc6s-v3

jobs:
  train:
    type: command
    component: file:../../components/image_translation/spec.yaml
    inputs:
      training_data:
        type: mltable
        path: azureml://datastores/workspaceblobstore/paths/vision-od/train/
      validation_data:
        type: mltable
        path: azureml://datastores/workspaceblobstore/paths/vision-od/valid/
      
      timeout_minutes: 60
      max_trials: 5
      
      sampling_alorithm: Random
      early_termination: Bandit
      delay_evaluation: 5

      
    resources:
      instance_count: 1
